import Head from "next/head";
import Image from "next/image";
import Gallery from "./Gallery";

import { useEffect, useState } from "react";
import Preload from "../../Components/Preload/Preload";

export default function HomeApp() {
  const [PreloadIsHidden, setPreloadIsHidden] = useState(false);

  useEffect(() => {
    let preloadTimeout = setTimeout(() => setPreloadIsHidden(true), 100);
    return () => {
      clearTimeout(preloadTimeout);
    };
  });

  return (
    <div>
      <Head>
        <title>ТПО «РЕЗЕРВ»</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {<Preload absolute {...{ PreloadIsHidden }} />}
      {PreloadIsHidden && <Gallery {...{ PreloadIsHidden }} />}
    </div>
  );
}
