import React, { useEffect } from "react";
import Head from "next/head";

import { useStore } from "../../Store/useStore";

import { projectData } from "../ProjectsLayout/data/data";

const PageHead = () => {
  const pageTitle = useStore((state) => state.pageTitle);

  useEffect(() => {
    console.log("pageTitle", pageTitle);
  }, [pageTitle]);

  return (
    <Head>
      <title>ТПО «РЕЗЕРВ»{pageTitle && ` — ${pageTitle}`}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      {projectData &&
        projectData.map(({ coverhor, coververt }, i) => {
          return (
            <>
              <link
                ref="preload"
                href={`/projects/Frame%20${coverhor}.jpg`}
              ></link>
              <link
                ref="preload"
                href={`/projects/Frame%20${coververt}.jpg`}
              ></link>
            </>
          );
        })}
    </Head>
  );
};

export default PageHead;
