import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "antd/dist/antd.css";

import Home from "./Pages/Home/index";
import { useEffect, useState } from "react";
import Preload from "../Components/Preload/Preload";

export default function HomeApp() {
  const [PreloadIsHidden, setPreloadIsHidden] = useState(false);

  useEffect(() => {
    let preloadTimeout = setTimeout(() => setPreloadIsHidden(true), 2500);
    return () => {
      clearTimeout(preloadTimeout);
    };
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!PreloadIsHidden && <Preload />}
      <Home />
    </div>
  );
}
